In [24]:
%pip install SQLAlchemy PyMySQL pandas

Requirement already satisfied: SQLAlchemy in C:\Users\mosta\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (2.0.52)
Requirement already satisfied: PyMySQL in C:\Users\mosta\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (1.2.0)
Requirement already satisfied: pandas in C:\Users\mosta\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (3.0.5)
Requirement already satisfied: greenlet>=1 in C:\Users\mosta\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from SQLAlchemy) (3.5.5)
Requirement already satisfied: typing-extensions>=4.6.0 in C:\Users\mosta\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from SQLAlchemy) (4.16.0)
Requirement already satisfied: numpy>=2.3.3 in C:\Users\mosta\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from pandas) (2.5.2)
Requirement already satisfied: python-dateutil>=2.8.2 in C:\Users\mosta\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in C:\Users\mosta\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from pandas) (2026.3)
Requirement already satisfied: six>=1.5 in C:\Users\mosta\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

In [25]:
import pandas as pd
from sqlalchemy import create_engine

In [ ]:
engine = create_engine(
    "mysql+pymysql://username:password@localhost:3306"
)

In [27]:
pd.read_sql("SHOW DATABASES", engine)

               Database
0      gaming_addiction
1                   hcv
2    information_schema
3                 mysql
4  parks_and_recreation
5    performance_schema
6                sakila
7                   sys
8                 world

In [28]:
tables = pd.read_sql(
    """
    SELECT
        TABLE_SCHEMA,
        TABLE_NAME
    FROM information_schema.TABLES
    WHERE TABLE_NAME = 'hcv_egy'
    """,
    engine
)

tables

  TABLE_SCHEMA TABLE_NAME
0          hcv    hcv_egy

**Load the entire table**

In [29]:
df = pd.read_sql(
    """
        SELECT * 
            FROM hcv.hcv_egy 
    """,
    engine
)

df

,Age,Gender,BMI,Fever,Nausea/Vomting,Headache,Diarrhea,Fatigue & generalized bone ache,Jaundice,Epigastric pain,...,ALT 36,ALT 48,ALT after 24 w,RNA Base,RNA 4,RNA 12,RNA EOT,RNA EF,Baseline histological Grading,Baselinehistological staging
0,56,1,35,2,1,1,1,2,2,2,...,5,5,5,655330,634536,288194,5,5,13,2
1,46,1,29,1,2,2,1,2,2,1,...,57,123,44,40620,538635,637056,336804,31085,4,2
2,57,1,33,2,2,2,2,1,1,1,...,5,5,5,571148,661346,5,735945,558829,4,4
3,49,2,33,1,2,1,2,1,2,1,...,48,77,33,1041941,449939,585688,744463,582301,10,3
4,59,1,32,1,1,2,1,2,2,2,...,94,90,30,660410,738756,3731527,338946,242861,11,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1380,44,1,29,1,2,2,2,1,1,1,...,63,44,45,387795,55938,5,5,5,15,4
1381,55,1,34,1,2,2,1,1,1,1,...,97,64,41,481378,152961,393339,73574,236273,10,2
1382,42,1,26,2,2,1,1,1,2,1,...,87,39,24,612664,572756,806109,343719,160457,6,2
1383,52,1,29,2,1,1,2,2,2,1,...,48,81,43,139872,76161,515730,2460,696074,15,3
1384,55,2,26,1,2,2,2,1,2,1,...,64,71,34,1190577,628730,5,5,5,13,3

**Patients age <= 40 ordered by BMI**

In [30]:
df_young = pd.read_sql(
    """
        SELECT * 
        FROM hcv.hcv_egy 
        WHERE Age <= 40 
        ORDER BY BMI
    """,
    engine)

df_young

,Age,Gender,BMI,Fever,Nausea/Vomting,Headache,Diarrhea,Fatigue & generalized bone ache,Jaundice,Epigastric pain,...,ALT 36,ALT 48,ALT after 24 w,RNA Base,RNA 4,RNA 12,RNA EOT,RNA EF,Baseline histological Grading,Baselinehistological staging
0,36,1,22,2,2,1,1,1,1,1,...,46,59,45,137712,1122999,561438,63145,806204,16,1
1,34,1,22,1,2,1,1,2,2,1,...,90,113,23,392976,884322,586834,182775,782154,9,2
2,32,1,22,1,2,2,2,1,1,1,...,78,112,30,521841,96063,5,5,5,6,1
3,33,1,22,1,1,1,2,1,1,1,...,65,82,43,243587,273075,592209,169057,19406,7,3
4,33,2,22,1,2,2,2,1,2,2,...,66,56,26,144825,1112542,716822,325884,598833,12,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
429,32,2,35,1,2,1,2,2,2,1,...,73,86,27,1095879,672692,463861,506313,501451,8,4
430,36,2,35,1,1,2,1,2,1,2,...,93,123,40,498269,3875,519485,761069,131805,14,2
431,35,1,35,2,1,2,1,1,1,2,...,64,108,28,228980,903786,802517,69016,69138,13,4
432,35,2,35,2,1,1,1,1,2,2,...,94,94,27,223117,808952,31690,393956,437691,14,1
433,34,1,35,1,2,1,1,1,1,2,...,110,72,35,483292,393236,126436,718912,366403,4,3

**Gender Distribution**

In [31]:
gender_distribution = pd.read_sql(
    """
        SELECT 
            Gender,
            COUNT(*) AS n,
            ROUND(AVG(Age), 1) AS avg_age,
            ROUND(AVG(BMI), 1) AS avg_bmi
        FROM hcv.hcv_egy
        GROUP BY Gender
        ORDER BY Gender
    """,
    engine
)

gender_distribution

   Gender    n  avg_age  avg_bmi
0       1  707     46.4     28.6
1       2  678     46.2     28.6

**Age Distribution**

In [32]:
age_distribution = pd.read_sql(
    """
        SELECT 
            CASE 
                WHEN Age < 40 THEN '<40' 
                WHEN Age < 50 THEN '40-49' 
                WHEN Age < 60 THEN '50-59' 
                ELSE '60+' 
            END AS age_group,
            COUNT(*) AS n 
        FROM hcv.hcv_egy 
        GROUP BY age_group 
        ORDER BY 
            CASE age_group 
                WHEN '<40' THEN 1 
                WHEN '40-49' THEN 2 
                WHEN '50-59' THEN 3 
                WHEN '60+' THEN 4 
            END
    """,
    engine
)

age_distribution

  age_group    n
0       <40  397
1     40-49  437
2     50-59  466
3       60+   85

**Fibrosis Stage Distribution**

In [33]:
fibrosis_distribution = pd.read_sql(
    """
        SELECT 
            `Baselinehistological staging` AS stage,
            COUNT(*) AS n,
            ROUND(
                100 * COUNT(*) / ( 
                    SELECT 
                        COUNT(*) 
                    FROM hcv.hcv_egy), 1) AS pct_of_patients 
        FROM hcv.hcv_egy
        GROUP BY `Baselinehistological staging` 
        ORDER BY stage
    """,
    engine
)

fibrosis_distribution

   stage    n  pct_of_patients
0      1  336             24.3
1      2  332             24.0
2      3  355             25.6
3      4  362             26.1

***Demographics + blood markers by fibrosis stage***

In [34]:
stage_demographics = pd.read_sql(
    """
    SELECT 
        `Baselinehistological staging` AS stage,
        COUNT(*) AS n,
        ROUND(AVG(Age), 1) AS avg_age,
        ROUND(AVG(BMI), 1) AS avg_bmi,
        ROUND(
            AVG(CASE 
                    WHEN Gender = 1 THEN 1 
                    ELSE 0 
                END) * 100,
            1
        ) AS pct_male,
        ROUND(AVG(WBC), 0) AS avg_wbc,
        ROUND(AVG(RBC), 0) AS avg_rbc,
        ROUND(AVG(HGB), 1) AS avg_hgb,
        ROUND(AVG(Plat), 0) AS avg_platelets
    FROM hcv.hcv_egy
    GROUP BY `Baselinehistological staging`
    ORDER BY stage
    """,
    engine
)

stage_demographics

,stage,n,avg_age,avg_bmi,pct_male,avg_wbc,avg_rbc,avg_hgb,avg_platelets
0,1,336,46.1,28.6,51.2,7497.0,4419634.0,12.6,157848.0
1,2,332,47.0,29.2,55.1,7523.0,4427173.0,12.5,160523.0
2,3,355,46.4,28.5,45.6,7446.0,4405213.0,12.5,158629.0
3,4,362,45.8,28.1,52.5,7662.0,4436410.0,12.6,156541.0

**Grading vs Staging relationship**

In [35]:
grading_staging = pd.read_sql(
    """
        SELECT 
            `Baselinehistological staging` AS stage,
            COUNT(*) AS n,
            ROUND(
                AVG(`Baseline histological Grading`),
                2
            ) AS avg_grade

        FROM hcv.hcv_egy
        GROUP BY `Baselinehistological staging`
        ORDER BY stage
    """, engine
)

grading_staging

   stage    n  avg_grade
0      1  336       9.98
1      2  332       9.88
2      3  355       9.74
3      4  362       9.47

**Symptoms & baseline liver enzymes by stage**

In [36]:
symptoms_liver = pd.read_sql(
    """
        SELECT 
            `Baselinehistological staging` AS stage,
            COUNT(*) AS n,
            ROUND(
                AVG(
                    CASE 
                        WHEN Fever = 2 THEN 1 
                        ELSE 0 
                    END
                ) * 100,
            1
            ) AS pct_fever,
            ROUND(
                AVG(
                    CASE 
                        WHEN Jaundice = 2 THEN 1 
                        ELSE 0 
                    END
                ) * 100,
            1
            ) AS pct_jaundice,
            ROUND(
                AVG(
                    CASE 
                        WHEN `Fatigue & generalized bone ache` = 2 THEN 1 
                        ELSE 0 
                    END
                ) * 100,
            1
            ) AS pct_fatigue,
            ROUND(AVG(`AST 1`), 1) AS avg_ast_baseline,
            ROUND(AVG(`ALT 1`), 1) AS avg_alt_baseline
        FROM hcv.hcv_egy
        GROUP BY `Baselinehistological staging`
        ORDER BY stage
    """,
    engine
)

symptoms_liver

,stage,n,pct_fever,pct_jaundice,pct_fatigue,avg_ast_baseline,avg_alt_baseline
0,1,336,53.3,46.7,47.9,83.1,82.4
1,2,332,51.8,53.6,52.1,83.2,84.2
2,3,355,53.0,48.7,48.2,83.9,83.5
3,4,362,48.3,51.4,51.4,81.0,85.5

**Percentile standing of baseline viral load within fibrosis stage**

In [37]:
viral_load_percentiles = pd.read_sql(
    """
        SELECT 
            `Baselinehistological staging` AS stage,
            `RNA BASE`,
            ROUND(
                PERCENT_RANK() OVER (
                    PARTITION BY `Baselinehistological staging`
                    ORDER BY `RNA BASE`
                ),
                3
            ) AS rank_in_stage,
            ROUND(
                CUME_DIST() OVER (
                    PARTITION BY `Baselinehistological staging`
                    ORDER BY `RNA BASE`
                ),
                3
            ) AS cume_dist_in_stage
        FROM hcv.hcv_egy
        ORDER BY 
            stage,
            `RNA BASE`
    """,
    engine
)

viral_load_percentiles

      stage  RNA BASE  rank_in_stage  cume_dist_in_stage
0         1      1009          0.000               0.003
1         1      4210          0.003               0.006
2         1      6677          0.006               0.009
3         1     15076          0.009               0.012
4         1     21844          0.012               0.015
...     ...       ...            ...                 ...
1380      4   1181651          0.989               0.989
1381      4   1181946          0.992               0.992
1382      4   1185460          0.994               0.994
1383      4   1191339          0.997               0.997
1384      4   1198310          1.000               1.000

[1385 rows x 4 columns]

**Rank patients by viral load within stage**

In [38]:
rank_patients = pd.read_sql(
    """
        SELECT
            `Baselinehistological staging` AS stage,
            `RNA BASE`,
            ROW_NUMBER() OVER (
                PARTITION BY `Baselinehistological staging`
                ORDER BY `RNA BASE` DESC
            ) AS row_num,
            RANK() OVER (
                PARTITION BY `Baselinehistological staging`
                ORDER BY `RNA BASE` DESC
            ) AS rnk,
            DENSE_RANK() OVER (
                PARTITION BY `Baselinehistological staging`
                ORDER BY `RNA BASE` DESC
            ) AS dense_rnk
        FROM hcv.hcv_egy
        ORDER BY stage, row_num;
    """,
    engine
)

rank_patients

      stage  RNA BASE  row_num  rnk  dense_rnk
0         1   1200762        1    1          1
1         1   1197511        2    2          2
2         1   1194301        3    3          3
3         1   1190662        4    4          4
4         1   1190483        5    5          5
...     ...       ...      ...  ...        ...
1380      4     27748      358  358        358
1381      4     23179      359  359        359
1382      4     23179      360  359        359
1383      4     12620      361  361        360
1384      4        11      362  362        361

[1385 rows x 5 columns]

**Response groups**

In [39]:
response_groups = pd.read_sql(
    """
        WITH response_class AS (
            SELECT 
                `Baselinehistological staging`,
                Age,
                BMI,
                Gender,
                `RNA 12`,
                `RNA EOT`,
                CASE
                    WHEN `RNA 12` <= 5 THEN 'Rapid responder'
                    WHEN `RNA EOT` <= 5 THEN 'EOT responder'
                    ELSE 'Non-responder'
                END AS response_group
            FROM hcv.hcv_egy
        ),

        group_stats AS (
            SELECT 
                response_group,
                COUNT(*) AS n,
                ROUND(AVG(Age), 1) AS avg_age,
                ROUND(AVG(BMI), 1) AS avg_bmi,
                ROUND(
                    100 * AVG(
                        CASE 
                            WHEN Gender = 1 THEN 1 
                            ELSE 0 
                        END
                    ),
                    1
                ) AS pct_male,
                ROUND(
                    AVG(`Baselinehistological staging`),
                    2
                ) AS avg_stage
            FROM response_class
            GROUP BY response_group
        )
        SELECT *,
            ROUND(
                100 * n / (
                    SELECT COUNT(*) 
                    FROM response_class
                ),
                1
            ) AS pct_of_total
        FROM group_stats
        ORDER BY n DESC
    """,
    engine
)

response_groups

    response_group    n  avg_age  avg_bmi  pct_male  avg_stage  pct_of_total
0    Non-responder  999     46.1     28.5      50.9       2.54          72.1
1  Rapid responder  385     46.8     28.8      51.4       2.52          27.8
2    EOT responder    1     56.0     35.0     100.0       2.00           0.1

**Baseline RNA quartiles vs EOT response**

In [40]:
rna_quartiles = pd.read_sql(
    """
        SELECT 
            rna_quartile,
            COUNT(*) AS n,
            ROUND(
                100 * AVG(
                    CASE 
                        WHEN `RNA EOT` <= 5 THEN 1 
                        ELSE 0 
                    END
                ),
                1
            ) AS pct_undetectable_eot
        FROM (
            SELECT 
                `RNA BASE`,
                `RNA EOT`,
                NTILE(4) OVER (
                    ORDER BY `RNA BASE`
                ) AS rna_quartile
            FROM hcv.hcv_egy
        ) AS t
        GROUP BY rna_quartile
        ORDER BY rna_quartile
    """,
    engine
)

rna_quartiles

   rna_quartile    n  pct_undetectable_eot
0             1  347                  28.8
1             2  346                  26.9
2             3  346                  28.3
3             4  346                  26.9

**Age with Fibrosis stage**

In [41]:
age_stage = pd.read_sql(
    """
        SELECT
            `Baselinehistological staging` AS stage,
            ROUND(AVG(Age), 2) AS avg_age
        FROM hcv.hcv_egy
        GROUP BY stage
        ORDER BY stage;
    """,
    engine
)

age_stage

   stage  avg_age
0      1    46.09
1      2    47.01
2      3    46.45
3      4    45.78

**BMI with fibrosis**

In [42]:
bmi_fibrosis = pd.read_sql(
    """
        SELECT
            `Baselinehistological staging` AS stage,
            ROUND(AVG(Plat), 2) AS avg_platelets
        FROM hcv.hcv_egy
        GROUP BY stage
        ORDER BY stage
    """,
    engine
)

bmi_fibrosis

   stage  avg_platelets
0      1      157848.49
1      2      160523.37
2      3      158629.20
3      4      156541.01

**viral load vs fibrosis**

In [43]:
load_fibrosis = pd.read_sql(
    """
        SELECT
            `Baselinehistological staging` AS stage,
            ROUND(AVG(`RNA BASE`), 2) AS avg_rna
        FROM hcv.hcv_egy
        GROUP BY stage
        ORDER BY stage
    """,
    engine
)

load_fibrosis

   stage    avg_rna
0      1  590487.67
1      2  565042.90
2      3  595218.45
3      4  610957.98

**Summary Table**

In [44]:
summary = pd.read_sql(
    """
        SELECT
            `Baselinehistological staging` AS stage,
            COUNT(*) AS patients,
            ROUND(AVG(Age), 1) AS avg_age,
            ROUND(AVG(BMI), 1) AS avg_bmi,
            ROUND(
                100 * AVG(
                    CASE WHEN Gender = 1 THEN 1 ELSE 0 END
                    ),
                1
                ) AS pct_male,
            ROUND(AVG(`AST 1`), 1) AS avg_ast,
            ROUND(AVG(`ALT 1`), 1) AS avg_alt,
            ROUND(AVG(Plat), 1) AS avg_platelets,
            ROUND(AVG(`RNA BASE`), 2) AS avg_baseline_rna,
            ROUND(
                100 * AVG(
                    CASE WHEN Fever = 2 THEN 1 ELSE 0 END
                ),
            1
            ) AS pct_fever,
            ROUND(
                100 * AVG(
                    CASE WHEN Jaundice = 2 THEN 1 ELSE 0 END
                ),
            1
            ) AS pct_jaundice
        FROM hcv.hcv_egy
        GROUP BY `Baselinehistological staging`
        ORDER BY stage;
    """,
    engine
)

summary

,stage,patients,avg_age,avg_bmi,pct_male,avg_ast,avg_alt,avg_platelets,avg_baseline_rna,pct_fever,pct_jaundice
0,1,336,46.1,28.6,51.2,83.1,82.4,157848.5,590487.67,53.3,46.7
1,2,332,47.0,29.2,55.1,83.2,84.2,160523.4,565042.90,51.8,53.6
2,3,355,46.4,28.5,45.6,83.9,83.5,158629.2,595218.45,53.0,48.7
3,4,362,45.8,28.1,52.5,81.0,85.5,156541.0,610957.98,48.3,51.4